version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0.0
jobs:
  one:
    executor: serverless/default
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo
      - aws-cli/setup
      - serverless/setup
      - run: npm install
      - run: sls deploy
workflows:
  one_and_two:
    jobs:
      - one
